### ISSUE TITLE
[Cypress] - Test service feature in UI

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#146]
The service feature has been introduced in the latest release.
https://docs.epinio.io/references/services
But it's not already in the UI, we have to wait for it before adding a new test in Cypress.

**Comment by juadk** [comment]
Comment from Richard about Service feature:
```Everything is ready to test except the catalog services page. At the moment it just displays a list, it'll be replaced with a snazzy one and page to view catalog service details. Everything else service related should be good to test though (creating, binding, etc)```

**Comment by juadk** [comment]
1. Create mysql service
![image](https://user-images.githubusercontent.com/6025636/173151427-2d5783f7-bad6-471a-9a0a-c36bf6dd2465.png)


2. Create application
![image](https://user-images.githubusercontent.com/6025636/173151874-d2174fb9-b843-43f6-b771-03e5b1100a31.png)
Make sure to bind the service to the app
![image](https://user-images.githubusercontent.com/6025636/173152038-2aec36cc-9b0e-4c3b-b738-fde8d5ad32f0.png)
Click on Create


3. Go to the URL
![image](https://user-images.githubusercontent.com/6025636/173152580-3cc7f5cc-deb1-4f31-9a60-27da9784efa9.png)
![image](https://user-images.githubusercontent.com/6025636/173152618-66f37caa-ce70-441a-a6f1-5b5aaff1c66f.png)

Fill the following fields:
![image](https://user-images.githubusercontent.com/6025636/173152905-866959f9-fb5a-4a0b-b0fb-ca38d84b5d2c.png)
`my_database `is the default name given to a sample database when you deploy mysql
The root password can be found in the configuration:
![image](https://user-images.githubusercontent.com/6025636/173153194-b72652cf-b410-4d28-8a55-aa1c3aba56f7.png)

The database host is the dns name of the mysql service: 
`x7c55b7d63a59a60c7e66662937a0-mysql.workspace.svc.cluster.local`
However, in the UI, it appears as the configuration name??? I doubt it.
![image](https://user-images.githubusercontent.com/6025636/173153537-4767ffa7-c36b-4fd8-bd73-fac332f2c866.png)

Click on submit and start the installation:
![image](https://user-images.githubusercontent.com/6025636/173153621-f1840bde-47ad-4873-a66d-096d9485aa7b.png)

Continue the wordpress website configuration and you will see your website.

**Comment by mmartin24** [comment]
While doing the steps for the automation, I noticed following the steps above the app was fully deployed but I could not "see" the application in the end. I tried uploading the app from folder, zip and git; got a couple of 401 errors and 1 database connection issue:
![image](https://user-images.githubusercontent.com/37271841/178457407-2df5a3cd-f5a3-4494-b186-b8ed427a9a11.png)
![image](https://user-images.githubusercontent.com/37271841/178457449-71eb4f3b-a020-4488-9a2b-f838aa07f06e.png)
![image](https://user-images.githubusercontent.com/37271841/178457674-d3114930-130b-4427-8b26-8e923e575ef9.png)

I am not sure if it is a bug, missconfiguration on my side or missing env var. About this last possibility I see in the [original wordpress installation](https://github.com/epinio/example-wordpress) instructions on step 7 this env var `CONFIG_NAME` that I am not seeing above. @juadk could this be the issue? If so, what is the expected value to be set in the UI?

Thanks

**Comment by mmartin24** [comment]
thanks @juadk .
As commented offline, adding for this particular case the env var: `CONFIG_NAME: x7c55b7d63a59a60c7e66662937a0-mysql` along with the 3 previous ones  seemed to worked:

![image](https://user-images.githubusercontent.com/37271841/178501053-b2d80622-39c7-4c72-ade6-08f11718724f.png)
I will configure the test like this.
