### ISSUE TITLE
[Cypress] - Changes needed for latest epinio-ui (v0.9.0-0.0.3)

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#174]
We got a new UI release and the Cypress code has to be adapted, this ticket summarizes things what we have to do:

- [ ] Add a test for the service feature - https://github.com/epinio/epinio-end-to-end-tests/issues/146
- [x] Change the menu check according to this screenshot: 
![image](https://user-images.githubusercontent.com/6025636/173001976-ab3a5a29-eeca-411d-aee6-9ddec2d0a0a4.png)

- [x] Now we have to click on Advanced settings to make Packeto builder image settings appear, and we can also add a check for Application chart 
![image](https://user-images.githubusercontent.com/6025636/173002574-1c2fd3d8-e318-473d-900e-0ab2aa1c7161.png)
![image](https://user-images.githubusercontent.com/6025636/173002619-f45807bf-3e54-4a3f-a46b-988311c7a35b.png)

- [x] Check the new welcome screen
![image](https://user-images.githubusercontent.com/6025636/173011912-5f727d72-074e-419c-a9bc-14b8434f210e.png)
That's not possible testing to create an application without any namespace created, that test has to be modified.

**Comment by mmartin24** [comment]
Closing this issue. Testing Service in #146 to be done aside
