### ISSUE TITLE
[Cypress] - Test to create new namespace from other resources creation screen 

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#180]
This is a new feature in the UI, we have now the ability to create a namespace when creating resources and it should be tested by Cypress.
![image](https://user-images.githubusercontent.com/6025636/174004000-5418f54d-8f24-47b5-9b4d-dbaeb231d140.png)

Enter a namespace name which does not exist yet:
![image](https://user-images.githubusercontent.com/6025636/174004252-7513a3c3-9339-4c25-9a14-fc2773deb1e0.png)

Continue the installation process and check that the resource will be deployed in the new namespace.

**Comment by mmartin24** [comment]
While working on the test automation of this issue I encounter a problem when running Cypress and attempting to create a Namespace on Services > Instances.

```
[Vue warn]: Invalid prop: type check failed for prop "to". Expected String, Object, got Location 

found in

---> <NuxtLink>
       <MastheadResourceDetail> at shell/components/ResourceDetail/Masthead.vue
         <CreateEditView> at shell/components/ResourceDetail/index.vue
           <EpinioResourceCreate> at pkg/epinio/pages/c/_cluster/_resource/create.vue
             <Nuxt>
               <Shell/layouts/default.vue> at shell/layouts/default.vue
                 <Root>
```


![Image](https://user-images.githubusercontent.com/37271841/174833219-e3932249-ae90-47f3-bb84-a67666f4c454.png)

This is only occurs with Cypress, manually the functionality is fine.
I am not sure what this could be

**Comment by mmartin24** [comment]
@richard-cox while installing npm on the dashboard repo I saw this error:

```
  dashboard git:(epinio-dev) ✗  npm audit fix
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dashboard@undefined
npm ERR! Found: vue-template-compiler@2.6.14
npm ERR! node_modules/vue-template-compiler
npm ERR!   dev vue-template-compiler@"2.6.14" from the root project
npm ERR!   dev vue-template-compiler@"^2.6.11" from @rancher/components@0.1.0-alpha.4
npm ERR!   pkg/rancher-components
npm ERR!     @rancher/components@0.1.0-alpha.4
npm ERR!     node_modules/@rancher/components
npm ERR!       workspace pkg/rancher-components from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue-template-compiler@"2.5.x" from require-extension-hooks-vue@3.0.0
npm ERR! node_modules/require-extension-hooks-vue
npm ERR!   require-extension-hooks-vue@"^3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Not sure if some extensions are required.
Is this something that needs to be added?

**Comment by richard-cox** [comment]
We use yarn, rather than npm (though the two are closely related). Updating dependencies though is something handled by the core dashboard team and changes would need to be done there (committed and tested). For normal running of the ui though `audit fix` isn't required.

**Comment by mmartin24** [comment]
> We use yarn, rather than npm (though the two are closely related). Updating dependencies though is something handled by the core dashboard team and changes would need to be done there (committed and tested). For normal running of the ui though `audit fix` isn't required.

you are actually right.
I actually normally use yarn install rather than npm. My mistake this tome. With yarn got warnings, not errors, but the issue still persist in Cypress

**Comment by mmartin24** [comment]
This issue as currently blocked.
Opened bug here: https://github.com/epinio/ui/issues/142

**Comment by thehejik** [comment]
I noticed something similar in rancher itself when installing epinio helm chart from there - cy.type does write `epinio` as a target namespace (for epinio installation) and it's somehow reverted back to `default` ns.

**Comment by mmartin24** [comment]
Check if this works after https://github.com/epinio/ui/issues/205 is fixed
