### ISSUE TITLE
[Cypress] - Rework Rancher UI CI workflow

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#186]
After having rework the [standalone UI workflow](https://github.com/epinio/epinio-end-to-end-tests/blob/main/.github/workflows/master_std_ui.yml) into only one job.
We will have to do the same for [Rancher UI workflow](https://github.com/epinio/epinio-end-to-end-tests/blob/main/.github/workflows/master_rancher_ui_workflow.yml).

**Comment by juadk** [comment]
I tried to install epinio through the marketplace and I managed to do it but once installed, I was not able to access to the epinio instance because the epinio logo does not appear in the nav-menu anymore.
Not sure if it's related to the issue Richard mentioned to me: https://github.com/epinio/ui/issues/129

**Comment by thehejik** [comment]
Closed in favour of https://github.com/epinio/epinio-end-to-end-tests/pull/233
