### ISSUE TITLE
[QA] Investigate failing Cypress UI tests at start

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#192]
We need to investigate flaky Cypress UI test standalone.
Although some errors vary, we had this error repeated both for `with_default_options.spec.ts` and `with_s3_and_external_registry.spec.ts` on 06/21/22:

![Image](https://user-images.githubusercontent.com/37271841/174758428-256e551d-8143-45af-9de7-3b6770be911c.png)

![Image](https://user-images.githubusercontent.com/37271841/174758533-2e361552-a20e-4fea-aaaa-2553e76cee86.png)

Checking the logs for [std-chrome](https://github.com/epinio/epinio-end-to-end-tests/runs/6977447036?check_suite_focus=true#step:13:215) and for [std-firefox](https://github.com/epinio/epinio-end-to-end-tests/runs/6977450091?check_suite_focus=true) I see:

```
 1) Menu testing
       "before each" hook for "Check Epinio menu":
     CypressError: `cy.visit()` failed trying to load:
https://host.docker.internal:8005/auth/login
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: ESOCKETTIMEDOUT
```

**Comment by mmartin24** [comment]
We need to investigate flaky Cypress UI test standalone.
Although some errors vary, we had this error repeated both for `with_default_options.spec.ts` and `with_s3_and_external_registry.spec.ts` on 06/21/22:



![Image](https://user-images.githubusercontent.com/37271841/174758428-256e551d-8143-45af-9de7-3b6770be911c.png)


![Image](https://user-images.githubusercontent.com/37271841/174758533-2e361552-a20e-4fea-aaaa-2553e76cee86.png)

Checking the logs for [std-chrome](https://github.com/epinio/epinio-end-to-end-tests/runs/6977447036?check_suite_focus=true#step:13:215) and for [std-firefox](https://github.com/epinio/epinio-end-to-end-tests/runs/6977450091?check_suite_focus=true) I see:

```
 1) Menu testing
       "before each" hook for "Check Epinio menu":
     CypressError: `cy.visit()` failed trying to load:
https://host.docker.internal:8005/auth/login
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: ESOCKETTIMEDOUT
```

**Comment by juadk** [comment]
I think the reason is that the dev dashboard setup is too long and when the first test starts, the dashboard is not ready yet.
I'm working on a solution to buid the dev dashboard before the test and push it as a docker image in a sandbox registry. Like that we won't rely on the build anymore. It should be ready today.
