### ISSUE TITLE
[Cypress] - Automate wordpress deployment using service to setup the db

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#197]
It could be interesting to automate that deployment to run it as a smoke test after a release or even before.
Instructions can be taken from https://github.com/epinio/epinio-end-to-end-tests/issues/146

**Comment by mmartin24** [comment]
This task is now covered in https://github.com/epinio/epinio-end-to-end-tests/issues/146
Closing issue
