### ISSUE TITLE
Find more examples of apps to be pushed for the Cypress tests

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#205]
It would be nice to expand the UI regression tests with more examples of apps.

**Comment by juadk** [comment]
It was my idea with https://github.com/epinio/epinio-end-to-end-tests/issues/197
Could be a good first one.

**Comment by mmartin24** [comment]
> It was my idea with #197 Could be a good first one.

That one is perfect to be added to automation already.
Apart from this, I was requested to find more.

**Comment by mmartin24** [comment]
Start gathering some samples and results here: https://confluence.suse.com/x/J4GZPQ

**Comment by mmartin24** [comment]
Closing after decided in QA meeting to check for more apps examples in case of client issue/request.
Opened this other task to check as possible UX improvement: https://github.com/epinio/epinio/issues/1627
