### ISSUE TITLE
Investigate Cypress Test Failing on STD-UI-Latest-Firefox

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#206]
STD-UI-Latest-Firefox tests failed after 3 attempts on 07/07/22 on namespaces unit test. 
The error seems to be related with this:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
---

Attempt1: https://github.com/epinio/epinio-end-to-end-tests/runs/7226677586?check_suite_focus=true#step:14:225

Preliminary check shows this error:
```
Status: Downloaded newer image for cypress/included:9.7.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[247:0707/035826.378902:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[247:0707/035826.387562:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

```

Attempt 2: https://github.com/epinio/epinio-end-to-end-tests/runs/7227165849?check_suite_focus=true#step:14:226
Same error, but after running with more logs it showed:

```
Makefile:86: warning: overriding recipe for target 'install-cert-manager'
Makefile:20: warning: ignoring old recipe for target 'install-cert-manager'
added 180 packages, and audited 181 packages in 11s
28 packages are looking for funding
  run `npm fund` for details
3 moderate severity vulnerabilities
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[245:0707/045419.886420:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[245:0707/045419.895597:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

Attempt 3: https://github.com/epinio/epinio-end-to-end-tests/runs/7227610851?check_suite_focus=true
Same error

**Comment by juadk** [comment]
From my point of view, those messages are not the root cause because I've always seen them, even when tests pass:
https://github.com/epinio/epinio-end-to-end-tests/runs/7208020917?check_suite_focus=true#step:14:35

And they also appear in the chrome test:
https://github.com/epinio/epinio-end-to-end-tests/runs/7227556232?check_suite_focus=true#step:14:132

My guess is rather this:

```
Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > Request aborted
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
https://on.cypress.io/uncaught-exception-from-application
Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Namespaces testing`
  1541/t.exports@https://epinio.10.162.231.173.omg.howdoi.website/_nuxt/310236d4ffcdbc9b7fef.js:2:3[70](https://github.com/epinio/epinio-end-to-end-tests/runs/7227610851?check_suite_focus=true#step:14:71)44
  1540/t.exports/</w.onabort@https://epinio.10.162.231.1[73](https://github.com/epinio/epinio-end-to-end-tests/runs/7227610851?check_suite_focus=true#step:14:74).omg.howdoi.website/_nuxt/310236d4ffcdbc9b7fef.js:2:35926
```

That's not the first time I can see it, but right now, I have no idea how to get more logs. Usually it passes after a restart.

**Comment by mmartin24** [comment]
You are right, that is also present when tests succeeds.
The error you mention is what you said, normally it shows at times on 1st run and then 2nd run disappears. 
Not sure why it did not this time.

**Comment by mmartin24** [comment]
Today it succeded after a second try:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2633750168

**Comment by mmartin24** [comment]
Today also day working from start: https://github.com/epinio/epinio-end-to-end-tests/runs/7275701078?check_suite_focus=true

**Comment by mmartin24** [comment]
Firefox tests were fixed and this is not occurring any longer
