### ISSUE TITLE
Investigate mutliple Pods appearing and disappearing when desired replicas is "1"

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#212]
Configuration test on STD Ui is failing since 07/27/22: https://github.com/epinio/epinio-end-to-end-tests/runs/7534320604?check_suite_focus=true

We need to investigate why and fix it

**Comment by mmartin24** [comment]
The issue here seems to be that the time taken since the unbinding of them takes place and the status goes back to 1/1 has increased to 30-40 seconds.

This can be seen in this video (start watching after 56s):  [status_time.zip](https://github.com/epinio/epinio-end-to-end-tests/files/9209173/status_time.zip).

The status sign stays different from 1/1 for over 30s:
![image](https://user-images.githubusercontent.com/37271841/181500799-0e4919b4-6153-4c8d-b15d-c67f9c1e9950.png)

I can easily fix this increasing the time in our UI tests, but before doing that I wanted to ask if we accept this as a normal behavior since it did not occur prior 07/26/22.

**Comment by mmartin24** [comment]
Summarizing here further investigation.
I checked this locally on Cypress test and manually and I always get status `4/1` that eventually (around 30s) goes down to `1/1`
expected.
Checking the response from `applications` on network logs I see `readyreplicas: 4`  and when looking each one of them only 1 seems to have some memory: `memoryBytes:41112384`. Pasting log and screenshot for clarity
![image](https://user-images.githubusercontent.com/37271841/181521419-93edbd5a-145d-4693-aa1b-6a73655aac29.png)

```
{
    "meta": {
        "name": "testapp",
        "namespace": "workspace",
        "createdAt": "2022-07-28T13:36:06Z"
    },
    "configuration": {
        "instances": 1,
        "configurations": [],
        "environment": {},
        "routes": [
            "testapp-a279f.172.19.0.3.omg.howdoi.website"
        ],
        "appchart": "standard"
    },
    "origin": {
        "Kind": 1,
        "git": {
            "repository": ""
        },
        "path": "sample-app.tar.gz"
    },
    "deployment": {
        "name": "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44",
        "active": true,
        "createdAt": "2022-07-28T13:36:35Z",
        "desiredreplicas": 1,
        "readyreplicas": 4,
        "replicas": {
            "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-76b59fb44m544": {
                "name": "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-76b59fb44m544",
                "memoryBytes": 4112384,
                "millicpus": 0,
                "createdAt": "2022-07-28T13:36:35Z",
                "restarts": 0,
                "ready": true
            },
            "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-76b59fb4gkxq2": {
                "name": "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-76b59fb4gkxq2",
                "memoryBytes": 0,
                "millicpus": 0,
                "createdAt": "2022-07-28T13:37:31Z",
                "restarts": 0,
                "ready": true
            },
            "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-76b59fb4snfq8": {
                "name": "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-76b59fb4snfq8",
                "memoryBytes": 0,
                "millicpus": 0,
                "createdAt": "2022-07-28T13:37:20Z",
                "restarts": 0,
                "ready": true
            },
            "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-7c67b69cd4rrg": {
                "name": "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-7c67b69cd4rrg",
                "memoryBytes": 0,
                "millicpus": 0,
                "createdAt": "2022-07-28T13:37:31Z",
                "restarts": 0,
                "ready": true
            }
        },
        "username": "admin",
        "stage_id": "8d868a83f0487739",
        "status": "4/1",
        "routes": [
            "testapp-a279f.172.19.0.3.omg.howdoi.website"
        ]
    },
    "status": "running",
    "statusmessage": "",
    "stage_id": "8d868a83f0487739",
    "image_url": "registry.epinio.svc.cluster.local:5000/apps/workspace-testapp:8d868a83f0487739"
}
```
I am not sure why this is produced, only that I can observe it.
@juadk , @jimmykarily, @andreas-kupries or anyone else , please let me know if there is something else that occurs to you for further troubleshoot. Please also let me know if we should handle fixing this `4/1` status in a separate ticket. 

Thanks

**Comment by mmartin24** [comment]
Yesterday I tried to check more information about the pods while the error was produced in k9s. I could not find anything clear. The only thing I saw and I am not sure if this is useful, this is the content of one of the 4 pods in `terminating` status right after the unbinding:

![2022-07-29_07-38](https://user-images.githubusercontent.com/37271841/181691131-76356b32-07c9-49ad-909d-a155a132c1db.png)

![2022-07-29_07-39](https://user-images.githubusercontent.com/37271841/181691208-b29e613b-5560-42c1-803a-e5d82e9fb756.png)

```
stream logs failed container "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44" in pod "rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-68b744bbfdjl6" is terminated for workspace/rtestapp-4a19557dc1b96c20dfa19772af36624f6913ae44-68b744bbfdjl6 (rtestapp-4a19557dc1b │
```
I am not sure if this throws any light into the issue.

**Comment by mmartin24** [comment]
As commented in standup today, it is not clear why these pods are being lifted and may be complicated to know without touching the actual code. Since this is something that may affect the functioning of the application I am removing the **QA** label. I am also setting the **help-wanted** one in case a developer can help troubleshoot this.

**Comment by jimmykarily** [comment]
This is the commit that causes this behavior : https://github.com/epinio/epinio/commit/7d7a997c4

**Comment by jimmykarily** [comment]
I tried to use the `Force` option instead of `Recreate` but it doesn't work when the previous operation is still pending (e.g. the previous push never completed because the app container was failing). An easy way to reproduce is to create a `Procfile` in the sample app directory that wouldn't work:

```
web: somethingsomething
```

I thinking, one way to solve this would be to check the status of the helm release before we decide whether to `Recreate` or not. If it's in failed state (or pending or other), then we should recreate. If it's deployed fine, we don't recreate.

**Comment by jimmykarily** [comment]
Trying to fix it here: https://github.com/epinio/epinio/tree/212-e2e-tests-fix-release-recreation
