### ISSUE TITLE
Update epinioteam/epinio-ui-qa:latest on run/commit/daily basis

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio-end-to-end-tests#223]
Found out that during testing of epinio-ui we are using outdated image `epinioteam/epinio-ui-qa:latest` which was built a month ago.

Ideally we would need to rebuilt and push the image on every new commit to UI. 

Eventally we should be able to build the image directly in our n2n workflows and use it directly for testing - it seems it was prepared for that as CI does checkout of dashboard and ui repos for some reason but the build step is missing there.

Related code.
https://github.com/epinio/epinio-end-to-end-tests/blob/c2b2833a427781ecd7ca0eb58b4088c11e36d254/.github/workflows/master_std_ui.yml#L115
https://github.com/epinio/epinio-end-to-end-tests/blob/main/scripts/patch_epinio-ui.sh

**Comment by mmartin24** [comment]
Thanks @thehejik ,
so as we commented offline, probably it is best to use the very latest released version 1.2.0 so we can run the tests with latest additions and disable latest qa image pull until it is fixed

**Comment by thehejik** [comment]
Actually we have this [workflow here](https://github.com/epinio/epinio-end-to-end-tests/blob/main/.github/workflows/build_latest_epinioUI.yml) for building and pushing the image - we just need to fix it.
