### ISSUE TITLE
[Cypress] Investigate why UI Github source test fails at fetching Epinio repo in CI

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#228]
Test for checking new Github source type was merged here: https://github.com/epinio/epinio-end-to-end-tests/pull/216
It worked locally, but could not be tested in CI because it was broken in its moment.

Now that CI is working again, it seems there is an issue fetching the repo in the moment that a repo name is added into the source. 
In [this](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3044719834/jobs/4905423642) CI, created brand new with only this test active, it can be checked how the repo fails to fetch the repo `epinio` shortly after is typed:

![Image](https://user-images.githubusercontent.com/37271841/189897101-d4cc64a1-772d-41eb-82ea-f0a03c4b9653.png)

It returns a 403 error on what seems to be this address

```
https://api.github.com/users/epinio/repos?sort=updated&amp;per_page=100&amp;direction=desc
```

The test works locally as can be seen: 

![Image](https://user-images.githubusercontent.com/37271841/189897704-29ddcfb9-13d6-45ea-89f5-98cb6518026d.png)

So I am not sure why fetching is prevented when running in CI

**Comment by mmartin24** [comment]
Pls note I really doubt it is a matter of exceeding the amount of requests to epinio repo, since this job was triggered from scratch and with one single test.

**Comment by thehejik** [comment]
Rate limit reached on our self-hosted github runners. This is a output from `curl -vvv https://api.github.com/users/epinio/repos?sort=updated\&amp;per_page=100\&amp;direction=desc` request
```
{"message":"API rate limit exceeded for re.da.ct.ed. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Comment by mmartin24** [comment]
Thanks @thehejik for the check.
Opened this issue for next steps: https://github.com/epinio/epinio/issues/1736

Closing this issue
