### ISSUE TITLE
Epinio UI test - Test Rancher dashboard 0.5.0

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#98]
@richard-cox has asked me to test latest epinio-v0.5.0.
I will run our Cypress tests on it.

**Comment by juadk** [comment]
Firefox test is ok with 0.5.0:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/1910584174

**Comment by juadk** [comment]
Ok this is what I got this morning:
Cypress tests fail when we try to access to Service page.
![image](https://user-images.githubusercontent.com/6025636/156151082-4e9e322e-67ca-4309-9e1e-910386fb168e.png)
Once we click on Service, it fails.

I was able to catch this in the console:
![image](https://user-images.githubusercontent.com/6025636/156151233-98cec9bd-dee6-4284-bd5a-a2324201c8d5.png)

I got the same with Namespace too.

After a lot of clicks... I reproduced it manually:
![image](https://user-images.githubusercontent.com/6025636/156152095-241a5e21-9b95-4610-8ab1-235e738091ec.png)

@richard-cox Any idea?

**Comment by juadk** [comment]
hmmm, if I add a small wait in the Cypress code (cy.wait(1000)) after the click on service, it works.
Maybe I'm wrong but on the second screenshot, it looks like we click on Service before the Polling started for services.

**Comment by richard-cox** [comment]
@juadk  `querySelector` is used on a reference to the root element in the list component. There could be a race condition where the element isn't ready when the reference is used. Are there steps to recreate outside of e2e tests?

**Comment by juadk** [comment]
> @juadk `querySelector` is used on a reference to the root element in the list component. There could be a race condition where the element isn't ready when the reference is used. Are there steps to recreate outside of e2e tests?

That's why my `cy.wait` fixes the issue.

Yes you can have a look at the third screenshot (the last one), I got `querySelector` after doing many clicks on Services, Namespaces, Services etc etc

I've never seen it before 0.5.0.

Do you think you can fix it or I simply have to add a wait command? (not very elegant though)

**Comment by richard-cox** [comment]
I've created https://github.com/rancher/dashboard/issues/5240. This is tagged as 2.6.4 but probably won't get fixed in time.

For the moment i'd suggest going with the wait command
